### ISSUE TITLE
Media Post Types

### ISSUE THREAD

**Issue by robhadfield** [satrya/recent-posts-widget-extended#9]
Hey - In the widget it's giving me an option for 'Media' post-type.

I don't see it handled in the code though - is this meant to be a filter for Media Library attachments? Would be great if it is.

I've added a taxonomy for my media so having an option to display a link to the latest media item in taxonomy 'Newsletter' would be great. Can this be done?

Cheers for the work on this - I use it a lot! :)
Rob

**Comment by robhadfield** [comment]
Thanks! :/

**Comment by satrya** [comment]
Oh, you still watching this ticket..haha, I'm so sorry. Please forgive me to not answer your question in two years

**Comment by robhadfield** [comment]
Sorry, only joking! :D

**Comment by satrya** [comment]
ok no worries :dancer: :smile:
